import "../../styles/globals.scss";
import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";

const exo_2 = Exo_2({
  subsets: ["latin"],
  weight: ["400", '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={exo_2.className}>
        {children}
      </body>
    </html>
  );
}
